### ISSUE TITLE
publishM2 also publishing html-binding-example-fastopt.js

### ISSUE THREAD

**Issue by mattisr** [kahliburke/html-binding-example#1]
I use this example as an template on how good it would be to replace parts of our Ajax based website with Binding.scala and Scala.js.

Our website is build with gradle and I need to get the generated js-file downloadable from a maven repo.

Would be great if you could show how to add html-binding-example-fastopt.js to the published artifacts.

I have tried to follow the sbt manual, but I really don't have a clue how to achive it.

**Comment by kahliburke** [comment]
I don't think this is an issue with the project, in general the output of a ScalaJS project won't include the generated JS files as they are sometimes combined in other libraries and bundled up together. See for example scala-js/scala-js/issues#1472. So you could just create another project that packages them into a WebJar as discussed in the comments of that issue.

**Comment by mattisr** [comment]
Thanks for the good Link.
